name: Release npm package

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
      - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: docker build --build-arg "$NPM_TOKEN" -t auto_release -f ./Dockerfile .
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
